server:
  port: 8080
spring:
  shardingsphere:
    datasource:
      names: db0, db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test1
        username: root
        password: root
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test2
        username: root
        password: root
    sharding:
      default-data-source-name: db0
      default-database-strategy:
        hint:
          algorithm-class-name: com.example.shardingspheredemo.sharding.DatabaseHintShardingAlgorithm
    props:
      sql:
        show: true